/// Flutter icons BodyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BodyIcons
///      fonts:
///       - asset: fonts/BodyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BodyIcons {
  BodyIcons._();

  static const _kFontFam = 'BodyIcons';

  static const IconData arm_flex = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData torso = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData abs = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData leg = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chest = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData butt_side = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData muscular_silhouette = const IconData(0xe808, fontFamily: _kFontFam);
}
