/// Flutter icons ChartIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChartIcons
///      fonts:
///       - asset: fonts/ChartIcons.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class ChartIcons {
  ChartIcons._();

  static const _kFontFam = 'ChartIcons';

  static const IconData signal = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData tasks = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData params = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData graphic_eq = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData poll = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pie_chart = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pie_chart_outlined = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData signal_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData chart_bar = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData chart_area_1 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData chart_1 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData chart_bar_2 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData chart_pie_1 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData signal_2 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData chart_bar_3 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData chart_pie_2 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData chart_pie_alt = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData chart_pie_outline = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData chart_pie_3 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData chart_bar_4 = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData chart_bar_outline = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData chart_alt = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData chart_alt_outline = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData chart_2 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData chart_outline = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData chart_pie_4 = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData chart_bar_5 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData show_chart = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData multiline_chart = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData insert_chart = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData gauge = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData chart_bars = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData sort_amount_asc = const IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData tasks_1 = const IconData(0xf0ae, fontFamily: _kFontFam);
  static const IconData chart_area = const IconData(0xf1fe, fontFamily: _kFontFam);
  static const IconData chart_pie = const IconData(0xf200, fontFamily: _kFontFam);
  static const IconData chart_line_1 = const IconData(0xf201, fontFamily: _kFontFam);
  static const IconData chart_bar_1 = const IconData(0xf526, fontFamily: _kFontFam);
}
