/// Flutter icons NavigationIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationIcons
///      fonts:
///       - asset: fonts/NavigationIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class NavigationIcons {
  NavigationIcons._();

  static const _kFontFam = 'NavigationIcons';

  static const IconData menu = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData chevron_up = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData arrow_up_circle = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData arrow_down_circle = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData arrow_left_circle = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData arrow_right_circle = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData chevron_up_circle = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData chevron_down_circle = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData chevron_left_circle = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData chevron_right_circle = const IconData(0xe88a, fontFamily: _kFontFam);
}
