/// Flutter icons TabsIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TabsIcons
///      fonts:
///       - asset: fonts/TabsIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class TabsIcons {
  TabsIcons._();

  static const _kFontFam = 'TabsIcons';

  static const IconData resize_vertical = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData resize_small_alt = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData balance_scale = const IconData(0xf24e, fontFamily: _kFontFam);
  

}
