/// Flutter icons ToolsIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToolsIcons
///      fonts:
///       - asset: fonts/ToolsIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class ToolsIcons {
  ToolsIcons._();

  static const _kFontFam = 'ToolsIcons';

  static const IconData calendar = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrow_drop_down_circle = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData updown_circle = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData calendar_1 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData calendar_2 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData calendar_3 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData calendar_full = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData chevron_up_circle = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData chevron_down_circle = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xf0b0, fontFamily: _kFontFam);
  static const IconData sort = const IconData(0xf0dc, fontFamily: _kFontFam);
  static const IconData calendar_empty = const IconData(0xf133, fontFamily: _kFontFam);
  static const IconData sort_alt_up = const IconData(0xf160, fontFamily: _kFontFam);
  static const IconData sort_alt_down = const IconData(0xf161, fontFamily: _kFontFam);
}
