/// Flutter icons WorkoutIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WorkoutIcons
///      fonts:
///       - asset: fonts/WorkoutIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WorkoutIcons {
  WorkoutIcons._();

  static const _kFontFam = 'WorkoutIcons';

  static const IconData barbell = const IconData(0xe800, fontFamily: _kFontFam); //1
  static const IconData dumbbell = const IconData(0xe801, fontFamily: _kFontFam); //2
  static const IconData running = const IconData(0xe802, fontFamily: _kFontFam); //3
  static const IconData bicycle = const IconData(0xe804, fontFamily: _kFontFam); //4
  static const IconData torch = const IconData(0xe806, fontFamily: _kFontFam); //5
  static const IconData yoga = const IconData(0xe807, fontFamily: _kFontFam); //6
  static const IconData stretching = const IconData(0xe808, fontFamily: _kFontFam); //7
  static const IconData swimming = const IconData(0xe809, fontFamily: _kFontFam); //8
  static const IconData walking = const IconData(0xe80a, fontFamily: _kFontFam); //9

  static const length = 9;
  static List<IconData> getWorkoutIcons(){
    return [dumbbell, running, stretching, barbell, swimming, yoga, walking, bicycle, torch];
  }
}
